[2024-04-16T16:01:58.124+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T16:01:58.197+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Superstore_dataprep_kuzmenko.data_prep_superstore manual__2024-04-16T16:01:51.050976+00:00 [queued]>
[2024-04-16T16:01:58.216+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Superstore_dataprep_kuzmenko.data_prep_superstore manual__2024-04-16T16:01:51.050976+00:00 [queued]>
[2024-04-16T16:01:58.218+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-16T16:01:58.275+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_prep_superstore> on 2024-04-16 16:01:51.050976+00:00
[2024-04-16T16:01:58.290+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T16:01:58.295+0000] {standard_task_runner.py:63} INFO - Started process 1165 to run task
[2024-04-16T16:01:58.293+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Superstore_dataprep_kuzmenko', 'data_prep_superstore', 'manual__2024-04-16T16:01:51.050976+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag_by_Kuzmenko.py', '--cfg-path', '/tmp/tmphcqzs59k']
[2024-04-16T16:01:58.297+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask data_prep_superstore
[2024-04-16T16:01:58.408+0000] {task_command.py:426} INFO - Running <TaskInstance: Superstore_dataprep_kuzmenko.data_prep_superstore manual__2024-04-16T16:01:51.050976+00:00 [running]> on host b3ab91a725a8
[2024-04-16T16:01:58.734+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='KuzmenkoSV' AIRFLOW_CTX_DAG_ID='Superstore_dataprep_kuzmenko' AIRFLOW_CTX_TASK_ID='data_prep_superstore' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T16:01:51.050976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-16T16:01:51.050976+00:00'
[2024-04-16T16:01:58.738+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T16:02:06.855+0000] {logging_mixin.py:188} INFO - [INFO] PostgreSQL connection closed
[2024-04-16T16:02:06.862+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-16T16:02:06.864+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T16:02:28.687+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Superstore_dataprep_kuzmenko, task_id=data_prep_superstore, execution_date=20240416T160151, start_date=20240416T160158, end_date=20240416T160228
[2024-04-16T16:02:28.833+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T16:02:28.895+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T16:02:28.907+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
