[2024-04-16T16:16:45.379+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T16:16:45.911+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Superstore_dataprep_kuzmenko.data_prep_superstore manual__2024-04-16T16:16:37.286617+00:00 [queued]>
[2024-04-16T16:16:46.236+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Superstore_dataprep_kuzmenko.data_prep_superstore manual__2024-04-16T16:16:37.286617+00:00 [queued]>
[2024-04-16T16:16:46.248+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-16T16:16:46.579+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_prep_superstore> on 2024-04-16 16:16:37.286617+00:00
[2024-04-16T16:16:46.623+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1335) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T16:16:46.627+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Superstore_dataprep_kuzmenko', 'data_prep_superstore', 'manual__2024-04-16T16:16:37.286617+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag_by_Kuzmenko.py', '--cfg-path', '/tmp/tmpa3fkzyli']
[2024-04-16T16:16:46.650+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask data_prep_superstore
[2024-04-16T16:16:46.649+0000] {standard_task_runner.py:63} INFO - Started process 1336 to run task
[2024-04-16T16:16:46.904+0000] {task_command.py:426} INFO - Running <TaskInstance: Superstore_dataprep_kuzmenko.data_prep_superstore manual__2024-04-16T16:16:37.286617+00:00 [running]> on host b3ab91a725a8
[2024-04-16T16:16:47.080+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='KuzmenkoSV' AIRFLOW_CTX_DAG_ID='Superstore_dataprep_kuzmenko' AIRFLOW_CTX_TASK_ID='data_prep_superstore' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T16:16:37.286617+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-16T16:16:37.286617+00:00'
[2024-04-16T16:16:47.084+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T16:16:55.726+0000] {logging_mixin.py:188} INFO - [INFO] PostgreSQL connection closed
[2024-04-16T16:16:55.728+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-16T16:16:55.729+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T16:16:55.747+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Superstore_dataprep_kuzmenko, task_id=data_prep_superstore, execution_date=20240416T161637, start_date=20240416T161645, end_date=20240416T161655
[2024-04-16T16:16:55.845+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T16:16:55.871+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T16:16:55.877+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
